name = "fear-and-greed-bot"
main = "src/index.js"
compatibility_date = "2023-10-30"
workers_dev = true
send_metrics = true

[triggers]
crons = ["0 14 * * *"]  # Runs every day at 14:00 UTC

[vars]
TELEGRAM_BOT_TOKEN_SECRET = "$TELEGRAM_BOT_TOKEN"

[[kv_namespaces]]
binding = "FEAR_GREED_KV"
id = "$FEAR_GREED_KV_NAMESPACE_ID"
